# Add your additional Hyprland configurations here

# Extra bindings
bind = $mainMod, SPACE, exec, pkill rofi || rofi -show drun -replace -i
bind = $mainMod, Z, exec, zeditor
bind = $mainMod, W, exec, zapzap
bind = $mainMod, A, exec, slack
bind = $mainMod, D, exec, discord
bind = $mainMod, Y, exec, youtube-music-desktop-app

# Custom keyboard layout
input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus=false
    touchpad {
        natural_scroll = false
        scroll_factor = 1.0  # Touchpad scroll factor
        disable_while_typing = false
    }
    sensitivity = 0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}

# Autostart
exec-once = ~/.scripts/autostart.sh

# Windowrules
windowrule = match:class org.manjaro.pamac.manager, float on
windowrule = match:class 1password, size 30% 50%, float on
